# Chapter 3. Introduction to Keras and TensorFlow

# Listing 3.1 All-ones or all-zeros tensors

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


# Listing 3.2 Random tensors

Tensor of random values drawn from a normal distribution
with mean 0 and standard deviation 1. Equivalent to
np.random.normal(size=(3, 1), loc=0., scale=1.).

In [4]:
x = tf.random.normal(shape=(3,1), mean=0, stddev=1.)
print(x)

tf.Tensor(
[[ 0.10469258]
 [-0.67587024]
 [ 0.83383787]], shape=(3, 1), dtype=float32)


Tensor of random values drawn from a uniform distribution between 0
and 1. Equivalent to np.random.uniform(size=(3, 1), low=0., high=1.).

In [5]:
x = tf.random.uniform(shape=(3,1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.29683542]
 [0.84059393]
 [0.38801098]], shape=(3, 1), dtype=float32)


A significant difference between NumPy arrays and TensorFlow tensors is that Tensor-
Flow tensors aren’t assignable: they’re constant. For instance, in NumPy, you can do
the following.

#### Listing 3.3 NumPy arrays are assignable

In [10]:
import numpy as np

x = np.ones(shape=(2,2))
print(x)

x[0,0] = 0
print(x)

[[1. 1.]
 [1. 1.]]
[[0. 1.]
 [1. 1.]]


Try to do the same thing in TensorFlow, and you will get an error: “EagerTensor object
does not support item assignment.”

#### Listing 3.4 TensorFlow tensors are not assignable

In [ ]:
x = tf.ones(shape=(2,2))
x[0, 0] = 0.  # This will fail, as a tensor isn’t assignable

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Note:  To train a model, we’ll need to update its state, which is a set of tensors. If tensors
aren’t assignable, how do we do it? That’s where variables come in. tf.Variable is the
class meant to manage modifiable state in TensorFlow.

#### Listing 3.5 Creating a TensorFlow variable

In [13]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.61630297],
       [-0.5659959 ],
       [ 0.02636   ]], dtype=float32)>


The state of a variable can be modified via its assign method, as follows.

#### Listing 3.6 Assigning a value to a TensorFlow variable

In [16]:
v.assign(tf.ones((3,1))) # It also works for a subset of the coefficients

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

#### Listing 3.7 Assigning a value to a subset of a TensorFlow variable

In [17]:
v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

Similarly, assign_add() and assign_sub() are efficient equivalents of += and -=, as
shown next.

#### Listing 3.8 Using assign_add() 

In [18]:
v.assign_add(tf.ones((3,1)))


<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

# 3.5.2 Tensor operations: Doing math in TensorFlow

Just like NumPy, TensorFlow offers a large collection of tensor operations to express
mathematical formulas.

#### Listing 3.9 A few basic math operations

Importantly, each of the preceding operations gets executed on the fly: at any point,
you can print what the current result is, just like in NumPy. We call this eager execution.

In [21]:
a = tf.ones((2,2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d

In [22]:
print(a)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [23]:
print(b)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [25]:
print(c)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [26]:
print(d)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [27]:
print(e)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


# 3.5.4 An end-to-end example: A linear classifier in pure TensorFlow